version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-v0"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12c0d4wom7vir"
s3_prefix = "sam-v0"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
