version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-v3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rzzoqd07unk2"
s3_prefix = "sam-v3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\" TableName=\"samv3\""
image_repositories = []
