version = 0.1

[default.deploy.parameters]
stack_name = "sam-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12c0d4wom7vir"
s3_prefix = "sam-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=dev"
